import Foundation

public enum TorrentCorePreviewFixtures {
    public static let checkedAt = Date(timeIntervalSince1970: 1_774_441_200)
    public static let torrentID = UUID(uuidString: "11111111-2222-3333-4444-555555555555")!

    public static let connectedHealth = TorrentCoreServiceHealth(
        apiVersion: 1,
        serviceName: "TorrentCore.Service",
        status: "ok",
        environmentName: "Preview",
        checkedAt: checkedAt
    )

    public static let hostStatus = TorrentCoreHostStatus(
        apiVersion: 1,
        serviceName: "TorrentCore.Service",
        serviceVersion: "1.0.0",
        serviceBuild: "0123456789abcdef0123456789abcdef01234567",
        serviceInstanceID: UUID(uuidString: "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"),
        engineRuntime: "MonoTorrent",
        engineListenPort: 55_123,
        engineDHTPort: 55_124,
        enginePortForwardingEnabled: true,
        engineLocalPeerDiscoveryEnabled: true,
        engineAllowPeerExchange: false,
        engineEncryptionMode: "EncryptedPreferred",
        engineMaximumConnections: 150,
        engineMaximumHalfOpenConnections: 8,
        engineMaximumDownloadRateBytesPerSecond: 0,
        engineMaximumUploadRateBytesPerSecond: 0,
        engineConnectionFailureLogBurstLimit: 5,
        engineConnectionFailureLogWindowSeconds: 60,
        maxActiveMetadataResolutions: 4,
        maxActiveDownloads: 4,
        availableMetadataResolutionSlots: 4,
        availableDownloadSlots: 3,
        resolvingMetadataCount: 0,
        metadataQueueCount: 0,
        downloadingCount: 1,
        downloadQueueCount: 0,
        seedingCount: 0,
        pausedCount: 0,
        completedCount: 0,
        errorCount: 0,
        currentConnectedPeerCount: 5,
        currentDownloadRateBytesPerSecond: 4_096_000,
        currentUploadRateBytesPerSecond: 512_000,
        partialFilesEnabled: true,
        partialFileSuffix: ".!mt",
        seedingStopMode: "Unlimited",
        seedingStopRatio: 1,
        seedingStopMinutes: 60,
        completedTorrentCleanupMode: "Never",
        completedTorrentCleanupMinutes: 60,
        deleteLogsForCompletedTorrents: false,
        status: .ready,
        environmentName: "Preview",
        downloadRootPath: "/preview/downloads",
        torrentCount: 1,
        supportsMagnetAdds: true,
        supportsPause: true,
        supportsResume: true,
        supportsRemove: true,
        supportsPersistentStorage: true,
        supportsMultiHost: false,
        startupRecoveryCompleted: true,
        startupRecoveredTorrentCount: 0,
        startupNormalizedTorrentCount: 0,
        startupRecoveryCompletedAt: checkedAt,
        vpnValidationEnabled: true,
        vpnConnectionPhase: "Ready",
        vpnConnectionReason: nil,
        torrentProcessingAvailable: true,
        torrentProcessingMessage: nil,
        vpnLastCheckAt: checkedAt,
        vpnLastSuccessAt: checkedAt,
        vpnNextAutomaticRetryAt: checkedAt.addingTimeInterval(240),
        vpnObservedPublicIPv4: "203.0.113.44",
        vpnDegradedCheckIntervalSeconds: 60,
        vpnReadyCheckIntervalSeconds: 240,
        vpnFailureSummary: nil,
        expressVPNRecoveryMode: "DirectIspOnly",
        expressVPNRecoveryPhase: "Inactive",
        expressVPNConnectionState: "Connected",
        expressVPNReconnectAttemptsUsed: 0,
        expressVPNReconnectAttemptsMaximum: 2,
        expressVPNLaunchAttemptsUsed: 0,
        expressVPNLaunchAttemptsMaximum: 2,
        expressVPNNextActionAt: nil,
        expressVPNLastActionAt: nil,
        expressVPNLastActionOutcome: nil,
        expressVPNRecoveryMessage: nil,
        checkedAt: checkedAt
    )

    public static let dashboardLifecycle = TorrentCoreDashboardLifecycle(
        callbackFailedCount: 0,
        callbackInvokedCount: 0,
        callbackTimedOutCount: 0,
        completedAutoRemovedCount: 0,
        firstEventAt: nil,
        lastEventAt: nil,
        metadataRefreshRequestedCount: 0,
        metadataResetRequestedCount: 0,
        metadataResolvedCount: 0,
        metadataRestartRequestedCount: 0,
        orphanedTorrentLogsDeletedCount: 0,
        recentEvents: [],
        recoveryCompletedAt: checkedAt,
        serviceInstanceID: hostStatus.serviceInstanceID,
        startupNormalizedTorrentCount: 0,
        startupReadyAt: checkedAt,
        startupRecoveredTorrentCount: 0,
        torrentsAddedCount: 1,
        torrentsRemovedCount: 0
    )

    public static let downloadingTorrent = TorrentCoreTorrentSummary(
        addedAt: checkedAt.addingTimeInterval(-3_600),
        canPause: true,
        canRefreshMetadata: false,
        canRemove: true,
        canResume: false,
        canRetryCompletionCallback: false,
        categoryKey: "tv",
        completedAt: nil,
        completionCallbackInvokedAt: nil,
        completionCallbackLastError: nil,
        completionCallbackPendingSince: nil,
        completionCallbackState: nil,
        connectedPeerCount: 5,
        downloadRateBytesPerSecond: 4_096_000,
        downloadedBytes: 524_288_000,
        errorMessage: nil,
        lastActivityAt: checkedAt,
        name: "Preview Torrent",
        progressPercent: 50,
        queuePosition: nil,
        state: .downloading,
        torrentID: torrentID,
        totalBytes: 1_048_576_000,
        trackerCount: 2,
        uploadRateBytesPerSecond: 512_000,
        waitReason: nil
    )

    public static let pausedTorrent: TorrentCoreTorrentSummary = {
        var torrent = downloadingTorrent
        torrent.name = "Paused Preview Torrent"
        torrent.state = .paused
        torrent.canPause = false
        torrent.canResume = true
        torrent.downloadRateBytesPerSecond = 0
        torrent.uploadRateBytesPerSecond = 0
        torrent.connectedPeerCount = 0
        torrent.waitReason = .pausedByOperator
        torrent.torrentID = UUID(uuidString: "66666666-7777-8888-9999-aaaaaaaaaaaa")
        return torrent
    }()

    public static let torrentDetail = TorrentCoreTorrentDetail(
        addedAt: downloadingTorrent.addedAt,
        canPause: true,
        canRefreshMetadata: false,
        canRemove: true,
        canResume: false,
        canRetryCompletionCallback: false,
        categoryKey: "tv",
        completedAt: nil,
        completionCallbackFeedback: nil,
        completionCallbackFinalPayloadPath: nil,
        completionCallbackInvokedAt: nil,
        completionCallbackLastError: nil,
        completionCallbackPendingReason: nil,
        completionCallbackPendingSince: nil,
        completionCallbackState: nil,
        connectedPeerCount: 5,
        downloadRateBytesPerSecond: 4_096_000,
        downloadedBytes: 524_288_000,
        errorMessage: nil,
        infoHash: "0123456789abcdef0123456789abcdef01234567",
        lastActivityAt: checkedAt,
        magnetURI: "magnet:?xt=urn:btih:0123456789abcdef0123456789abcdef01234567",
        name: "Preview Torrent",
        progressPercent: 50,
        queuePosition: nil,
        savePath: "/preview/downloads/Preview Torrent",
        state: .downloading,
        torrentID: torrentID,
        totalBytes: 1_048_576_000,
        trackerCount: 2,
        uploadRateBytesPerSecond: 512_000,
        waitReason: nil
    )

    public static let categories = [
        TorrentCoreCategory(
            callbackLabel: "TV Show",
            displayName: "TV (Show)",
            downloadRootPath: "/preview/downloads/tv",
            enabled: true,
            invokeCompletionCallback: true,
            key: "tv",
            sortOrder: 10
        ),
        TorrentCoreCategory(
            callbackLabel: "Movie",
            displayName: "Movie",
            downloadRootPath: "/preview/downloads/movies",
            enabled: true,
            invokeCompletionCallback: true,
            key: "movie",
            sortOrder: 20
        ),
    ]

    public static let history = [
        TorrentCoreHistorySummary(
            categoryKey: "tv",
            completionCallbackFinalResult: nil,
            dataDeleted: false,
            downloadCompletedAt: nil,
            downloadRootPath: "/preview/downloads/tv",
            downloadStartedAt: checkedAt.addingTimeInterval(-3_300),
            infoHash: "0123456789abcdef0123456789abcdef01234567",
            lastActivityAt: checkedAt,
            lastUpdatedAt: checkedAt,
            latestCallbackStatus: nil,
            latestConnectedPeerCount: 5,
            latestDownloadRateBytesPerSecond: 4_096_000,
            latestDownloadedBytes: 524_288_000,
            latestErrorMessage: nil,
            latestProgressPercent: 50,
            latestTorrentState: "Downloading",
            latestTotalBytes: 1_048_576_000,
            latestTrackerCount: 2,
            latestUploadRateBytesPerSecond: 512_000,
            latestUploadedBytes: 32_768_000,
            latestWaitReason: nil,
            metadataResolvedAt: checkedAt.addingTimeInterval(-3_400),
            name: "Preview Torrent",
            outcome: .active,
            removalKind: nil,
            removalReason: nil,
            removedAt: nil,
            removedByCleanupPolicy: false,
            seedingStartedAt: nil,
            submittedAt: checkedAt.addingTimeInterval(-3_600),
            torrentID: torrentID
        ),
        TorrentCoreHistorySummary(
            categoryKey: "movie",
            completionCallbackFinalResult: "Success",
            dataDeleted: false,
            downloadCompletedAt: checkedAt.addingTimeInterval(-90_000),
            downloadRootPath: "/preview/downloads/movies",
            downloadStartedAt: checkedAt.addingTimeInterval(-94_000),
            infoHash: "89abcdef0123456789abcdef0123456789abcdef",
            lastActivityAt: checkedAt.addingTimeInterval(-86_500),
            lastUpdatedAt: checkedAt.addingTimeInterval(-86_400),
            latestCallbackStatus: "Completed",
            latestConnectedPeerCount: 0,
            latestDownloadRateBytesPerSecond: 0,
            latestDownloadedBytes: 2_147_483_648,
            latestErrorMessage: nil,
            latestProgressPercent: 100,
            latestTorrentState: "Removed",
            latestTotalBytes: 2_147_483_648,
            latestTrackerCount: 3,
            latestUploadRateBytesPerSecond: 0,
            latestUploadedBytes: 268_435_456,
            latestWaitReason: nil,
            metadataResolvedAt: checkedAt.addingTimeInterval(-95_000),
            name: "Completed Preview Movie",
            outcome: .removed,
            removalKind: .manualRemoval,
            removalReason: "Removed by operator.",
            removedAt: checkedAt.addingTimeInterval(-86_400),
            removedByCleanupPolicy: false,
            seedingStartedAt: checkedAt.addingTimeInterval(-90_000),
            submittedAt: checkedAt.addingTimeInterval(-96_000),
            torrentID: UUID(uuidString: "bbbbbbbb-cccc-dddd-eeee-ffffffffffff")
        ),
        TorrentCoreHistorySummary(
            categoryKey: "tv",
            completionCallbackFinalResult: nil,
            dataDeleted: false,
            downloadCompletedAt: nil,
            downloadRootPath: "/preview/downloads/tv",
            downloadStartedAt: checkedAt.addingTimeInterval(-180_000),
            infoHash: "fedcba9876543210fedcba9876543210fedcba98",
            lastActivityAt: checkedAt.addingTimeInterval(-176_000),
            lastUpdatedAt: checkedAt.addingTimeInterval(-172_800),
            latestCallbackStatus: nil,
            latestConnectedPeerCount: 0,
            latestDownloadRateBytesPerSecond: 0,
            latestDownloadedBytes: 12_000_000,
            latestErrorMessage: nil,
            latestProgressPercent: 2,
            latestTorrentState: "Stopped",
            latestTotalBytes: 600_000_000,
            latestTrackerCount: 2,
            latestUploadRateBytesPerSecond: 0,
            latestUploadedBytes: 0,
            latestWaitReason: "NoPeers",
            metadataResolvedAt: checkedAt.addingTimeInterval(-181_000),
            name: "Abandoned Preview Episode",
            outcome: .abandoned,
            removalKind: .coldDownloadAbandonment,
            removalReason: "No useful download activity before the abandonment threshold.",
            removedAt: checkedAt.addingTimeInterval(-172_800),
            removedByCleanupPolicy: true,
            seedingStartedAt: nil,
            submittedAt: checkedAt.addingTimeInterval(-182_000),
            torrentID: UUID(uuidString: "12121212-3434-5656-7878-909090909090")
        ),
    ]

    public static let completionCallbackFeedback = TorrentCoreCompletionCallbackFeedback(
        allowResubmit: false,
        attemptCount: 1,
        callbackFinished: true,
        callbackLocalTimestamp: checkedAt.addingTimeInterval(-85_800),
        callbackMachine: "ca-desktop",
        callbackSource: "TVMaze",
        completionTimestamp: checkedAt.addingTimeInterval(-86_400),
        contractVersion: "1",
        correlationID: "preview-callback",
        detailMessage: "TVMaze accepted the completed download.",
        displayMessage: "TVMaze accepted the completed download.",
        finalState: "Success",
        mediaConsideredDone: true,
        needsManualIntervention: false,
        rawResponseJSON: nil,
        reasonCode: "Imported",
        receivedAt: checkedAt.addingTimeInterval(-85_800),
        recommendedAction: nil,
        resubmitAdvice: nil,
        sourceState: "Completed",
        torrentHash: "89abcdef0123456789abcdef0123456789abcdef",
        torrentID: UUID(uuidString: "bbbbbbbb-cccc-dddd-eeee-ffffffffffff")
    )

    public static let historyDetail = TorrentCoreHistoryDetail(
        callbackCompletedAt: checkedAt.addingTimeInterval(-85_800),
        callbackLastError: nil,
        callbackStartedAt: checkedAt.addingTimeInterval(-86_400),
        categoryKey: "tv",
        completionCallbackFeedback: completionCallbackFeedback,
        completionCallbackLabel: "TV Show",
        dataDeleted: false,
        downloadCompletedAt: nil,
        downloadRootPath: "/preview/downloads/tv",
        downloadStartedAt: checkedAt.addingTimeInterval(-3_300),
        finalPayloadPath: nil,
        infoHash: "0123456789abcdef0123456789abcdef01234567",
        invokeCompletionCallback: true,
        lastActivityAt: checkedAt,
        lastUpdatedAt: checkedAt,
        latestCallbackStatus: nil,
        latestConnectedPeerCount: 5,
        latestDownloadRateBytesPerSecond: 4_096_000,
        latestDownloadedBytes: 524_288_000,
        latestErrorMessage: nil,
        latestProgressPercent: 50,
        latestTorrentState: "Downloading",
        latestTotalBytes: 1_048_576_000,
        latestTrackerCount: 2,
        latestUploadRateBytesPerSecond: 512_000,
        latestUploadedBytes: 32_768_000,
        latestWaitReason: nil,
        magnetURI: torrentDetail.magnetURI,
        metadataResolvedAt: checkedAt.addingTimeInterval(-3_400),
        name: "Preview Torrent",
        outcome: .active,
        removalKind: nil,
        removalReason: nil,
        removedAt: nil,
        removedByCleanupPolicy: false,
        seedingStartedAt: nil,
        serviceInstanceIDLastSeen: hostStatus.serviceInstanceID,
        submittedAt: checkedAt.addingTimeInterval(-3_600),
        torrentID: torrentID
    )

    public static let activityLogs = [
        TorrentCoreActivityLogEntry(
            category: "Torrent",
            detailsJSON: #"{"state":"Downloading","progressPercent":50}"#,
            eventType: "TorrentStateChanged",
            level: "Information",
            logEntryID: 3,
            message: "Preview Torrent is downloading.",
            occurredAt: checkedAt,
            serviceInstanceID: hostStatus.serviceInstanceID,
            torrentID: torrentID,
            traceID: "preview-torrent-trace"
        ),
        TorrentCoreActivityLogEntry(
            category: "Tracker",
            detailsJSON: nil,
            eventType: "AnnounceWarning",
            level: "Warning",
            logEntryID: 2,
            message: "One preview tracker has not announced yet.",
            occurredAt: checkedAt.addingTimeInterval(-120),
            serviceInstanceID: hostStatus.serviceInstanceID,
            torrentID: torrentID,
            traceID: nil
        ),
        TorrentCoreActivityLogEntry(
            category: "Host",
            detailsJSON: nil,
            eventType: "StartupReady",
            level: "Information",
            logEntryID: 1,
            message: "Fixture TorrentCore service is ready.",
            occurredAt: checkedAt.addingTimeInterval(-300),
            serviceInstanceID: hostStatus.serviceInstanceID,
            torrentID: nil,
            traceID: "preview-startup-trace"
        ),
    ]

    public static let peers = [
        TorrentCorePeer(
            client: "MonoTorrent",
            direction: "Outgoing",
            downloadRateBytesPerSecond: 2_500_000,
            downloadedBytes: 300_000_000,
            encryption: "RC4Full",
            endpoint: "192.0.2.10:51413",
            isConnected: true,
            isSeeder: false,
            uploadRateBytesPerSecond: 120_000,
            uploadedBytes: 9_000_000
        ),
        TorrentCorePeer(
            client: "qBittorrent",
            direction: "Incoming",
            downloadRateBytesPerSecond: 1_596_000,
            downloadedBytes: 224_288_000,
            encryption: "PlainText",
            endpoint: "198.51.100.20:6881",
            isConnected: true,
            isSeeder: true,
            uploadRateBytesPerSecond: 392_000,
            uploadedBytes: 23_768_000
        ),
    ]

    public static let trackers = [
        TorrentCoreTracker(
            canAnnounce: true,
            canScrape: true,
            failureMessage: nil,
            isActive: true,
            lastAnnounceSucceeded: true,
            lastScrapeSucceeded: true,
            status: "OK",
            tierNumber: 0,
            timeSinceLastAnnounceSeconds: 45,
            timeSinceLastScrapeSeconds: 180,
            trackerNumber: 0,
            warningMessage: nil
        ),
        TorrentCoreTracker(
            canAnnounce: true,
            canScrape: false,
            failureMessage: nil,
            isActive: false,
            lastAnnounceSucceeded: nil,
            lastScrapeSucceeded: nil,
            status: "NotAnnounced",
            tierNumber: 1,
            timeSinceLastAnnounceSeconds: nil,
            timeSinceLastScrapeSeconds: nil,
            trackerNumber: 0,
            warningMessage: "Waiting for the next announce interval."
        ),
    ]

    public static let runtimeSettings = TorrentCoreRuntimeSettings(
        appliedEngineAllowPeerExchange: false,
        appliedEngineEncryptionMode: "EncryptedPreferred",
        appliedEngineMaximumConnections: 150,
        appliedEngineMaximumDownloadRateBytesPerSecond: 0,
        appliedEngineMaximumHalfOpenConnections: 8,
        appliedEngineMaximumUploadRateBytesPerSecond: 0,
        automaticMetadataResetStuckThresholdSeconds: 30,
        coldDownloadAbandonAfterHours: 48,
        coldDownloadRecoveryIntervalMinutes: 15,
        coldDownloadRecoveryThresholdMinutes: 30,
        completedTorrentCleanupMinutes: 60,
        completedTorrentCleanupMode: "Never",
        completionCallbackAPIBaseURLOverride: nil,
        completionCallbackAPIKeyOverride: nil,
        completionCallbackArguments: nil,
        completionCallbackCommandPath: nil,
        completionCallbackEnabled: true,
        completionCallbackFinalizationTimeoutSeconds: 300,
        completionCallbackTimeoutSeconds: 60,
        completionCallbackWorkingDirectory: nil,
        deleteLogsForCompletedTorrents: false,
        engineConnectionFailureLogBurstLimit: 5,
        engineConnectionFailureLogWindowSeconds: 60,
        engineAllowPeerExchange: false,
        engineEncryptionMode: "EncryptedPreferred",
        engineMaximumConnections: 150,
        engineMaximumDownloadRateBytesPerSecond: 0,
        engineMaximumHalfOpenConnections: 8,
        engineMaximumUploadRateBytesPerSecond: 0,
        engineRuntime: "MonoTorrent",
        engineSettingsRequireRestart: false,
        maxActiveDownloads: 4,
        maxActiveMetadataResolutions: 4,
        metadataRefreshRestartDelaySeconds: 5,
        metadataRefreshStaleSeconds: 300,
        metadataResolutionTimeSliceMinutes: 15,
        priorityMetadataAttempts: 3,
        partialFileSuffix: ".!mt",
        partialFilesEnabled: true,
        retrievedAt: checkedAt,
        seedingStopMinutes: 60,
        seedingStopMode: "Unlimited",
        seedingStopRatio: 1,
        supportsLiveUpdates: true,
        updatedAt: checkedAt.addingTimeInterval(-86_400),
        usesPersistedOverrides: true,
        expressVPNAutomaticRecoveryMode: "Disabled",
        expressVPNRecoveryDelaySeconds: 180,
        expressVPNUnavailableLaunchDelaySeconds: 300,
        vpnEgressDegradedCheckIntervalSeconds: 60,
        vpnEgressDirectIspCidrs: ["47.0.0.0/8"],
        vpnEgressReadyCheckIntervalSeconds: 240,
        vpnEgressRequestTimeoutSeconds: 10,
        vpnEgressEngineSuspensionTimeoutSeconds: 10,
        vpnEgressValidationEnabled: false,
        vpnEgressValidationEndpoint: "https://api.ipify.org?format=json",
        runtimeTickDurationSummaryEnabled: false
    )

    public static let restartResult = TorrentCoreServiceRestartResult(
        message: "TorrentCore service restart requested.",
        requestedAt: checkedAt,
        serviceLabel: "com.conadv.torrentcore.service"
    )

    public static let serviceProblem = TorrentCoreServiceProblem(
        type: "https://torrentcore.local/problems/unavailable",
        title: "Service unavailable",
        status: 503,
        detail: "TorrentCore is starting.",
        instance: nil,
        code: "host.not_ready",
        target: nil,
        traceID: "preview-trace",
        errors: [:]
    )

    public static func actionResult(
        action: String,
        state: TorrentCoreTorrentState,
        dataDeleted: Bool? = nil
    ) -> TorrentCoreActionResult {
        TorrentCoreActionResult(
            action: action,
            dataDeleted: dataDeleted,
            processedAt: checkedAt,
            state: state,
            torrentID: torrentID
        )
    }
}
